id: P47F999B1
initial_creation_type: input
source_metadata:
  title: Pādārthadharmasaṃgraha commentary on Kaṇāda's Vaiśeṣikasūtra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vaiśeṣika
  data entry: Muneo Tokunaga
  contribution to GRETIL: Muneo Tokunaga
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:04:26.250178'
last_modified_at: '2022-03-09T15:04:26.250190'
